const pool = require('./connection');

const provinces = [
  { code: '11', name: 'Aceh' },
  { code: '12', name: 'Sumatera Utara' },
  { code: '13', name: 'Sumatera Barat' },
  { code: '14', name: 'Riau' },
  { code: '15', name: 'Jambi' },
  { code: '16', name: 'Sumatera Selatan' },
  { code: '17', name: 'Bengkulu' },
  { code: '18', name: 'Lampung' },
  { code: '19', name: 'Kepulauan Bangka Belitung' },
  { code: '21', name: 'Kepulauan Riau' },
  { code: '31', name: 'DKI Jakarta' },
  { code: '32', name: 'Jawa Barat' },
  { code: '33', name: 'Jawa Tengah' },
  { code: '34', name: 'DI Yogyakarta' },
  { code: '35', name: 'Jawa Timur' },
  { code: '36', name: 'Banten' },
  { code: '51', name: 'Bali' },
  { code: '52', name: 'Nusa Tenggara Barat' },
  { code: '53', name: 'Nusa Tenggara Timur' },
  { code: '61', name: 'Kalimantan Barat' },
  { code: '62', name: 'Kalimantan Tengah' },
  { code: '63', name: 'Kalimantan Selatan' },
  { code: '64', name: 'Kalimantan Timur' },
  { code: '65', name: 'Kalimantan Utara' },
  { code: '71', name: 'Sulawesi Utara' },
  { code: '72', name: 'Sulawesi Tengah' },
  { code: '73', name: 'Sulawesi Selatan' },
  { code: '74', name: 'Sulawesi Tenggara' },
  { code: '75', name: 'Gorontalo' },
  { code: '76', name: 'Sulawesi Barat' },
  { code: '81', name: 'Maluku' },
  { code: '82', name: 'Maluku Utara' },
  { code: '91', name: 'Papua' },
  { code: '92', name: 'Papua Barat' },
  { code: '93', name: 'Papua Selatan' },
  { code: '94', name: 'Papua Tengah' },
  { code: '95', name: 'Papua Pegunungan' },
  { code: '96', name: 'Papua Barat Daya' },
];

const kabupatenData = {
  '11': [
    { code: '1101', name: 'Kabupaten Aceh Selatan', type: 'kabupaten' },
    { code: '1102', name: 'Kabupaten Aceh Tenggara', type: 'kabupaten' },
    { code: '1103', name: 'Kabupaten Aceh Timur', type: 'kabupaten' },
    { code: '1104', name: 'Kabupaten Aceh Tengah', type: 'kabupaten' },
    { code: '1105', name: 'Kabupaten Aceh Barat', type: 'kabupaten' },
    { code: '1106', name: 'Kabupaten Aceh Besar', type: 'kabupaten' },
    { code: '1107', name: 'Kabupaten Pidie', type: 'kabupaten' },
    { code: '1108', name: 'Kabupaten Aceh Utara', type: 'kabupaten' },
    { code: '1109', name: 'Kabupaten Simeulue', type: 'kabupaten' },
    { code: '1110', name: 'Kabupaten Aceh Singkil', type: 'kabupaten' },
    { code: '1111', name: 'Kabupaten Bireuen', type: 'kabupaten' },
    { code: '1112', name: 'Kabupaten Aceh Barat Daya', type: 'kabupaten' },
    { code: '1113', name: 'Kabupaten Gayo Lues', type: 'kabupaten' },
    { code: '1114', name: 'Kabupaten Aceh Jaya', type: 'kabupaten' },
    { code: '1115', name: 'Kabupaten Nagan Raya', type: 'kabupaten' },
    { code: '1116', name: 'Kabupaten Aceh Tamiang', type: 'kabupaten' },
    { code: '1117', name: 'Kabupaten Bener Meriah', type: 'kabupaten' },
    { code: '1118', name: 'Kabupaten Pidie Jaya', type: 'kabupaten' },
    { code: '1171', name: 'Kota Banda Aceh', type: 'kota' },
    { code: '1172', name: 'Kota Sabang', type: 'kota' },
    { code: '1173', name: 'Kota Lhokseumawe', type: 'kota' },
    { code: '1174', name: 'Kota Langsa', type: 'kota' },
    { code: '1175', name: 'Kota Subulussalam', type: 'kota' },
  ],
  '12': [
    { code: '1201', name: 'Kabupaten Tapanuli Tengah', type: 'kabupaten' },
    { code: '1202', name: 'Kabupaten Tapanuli Utara', type: 'kabupaten' },
    { code: '1203', name: 'Kabupaten Tapanuli Selatan', type: 'kabupaten' },
    { code: '1204', name: 'Kabupaten Nias', type: 'kabupaten' },
    { code: '1205', name: 'Kabupaten Langkat', type: 'kabupaten' },
    { code: '1206', name: 'Kabupaten Karo', type: 'kabupaten' },
    { code: '1207', name: 'Kabupaten Deli Serdang', type: 'kabupaten' },
    { code: '1208', name: 'Kabupaten Simalungun', type: 'kabupaten' },
    { code: '1209', name: 'Kabupaten Asahan', type: 'kabupaten' },
    { code: '1210', name: 'Kabupaten Labuhanbatu', type: 'kabupaten' },
    { code: '1211', name: 'Kabupaten Dairi', type: 'kabupaten' },
    { code: '1212', name: 'Kabupaten Toba', type: 'kabupaten' },
    { code: '1213', name: 'Kabupaten Mandailing Natal', type: 'kabupaten' },
    { code: '1214', name: 'Kabupaten Nias Selatan', type: 'kabupaten' },
    { code: '1215', name: 'Kabupaten Pakpak Bharat', type: 'kabupaten' },
    { code: '1216', name: 'Kabupaten Humbang Hasundutan', type: 'kabupaten' },
    { code: '1217', name: 'Kabupaten Samosir', type: 'kabupaten' },
    { code: '1218', name: 'Kabupaten Serdang Bedagai', type: 'kabupaten' },
    { code: '1219', name: 'Kabupaten Batu Bara', type: 'kabupaten' },
    { code: '1220', name: 'Kabupaten Padang Lawas Utara', type: 'kabupaten' },
    { code: '1221', name: 'Kabupaten Padang Lawas', type: 'kabupaten' },
    { code: '1222', name: 'Kabupaten Labuhanbatu Selatan', type: 'kabupaten' },
    { code: '1223', name: 'Kabupaten Labuhanbatu Utara', type: 'kabupaten' },
    { code: '1224', name: 'Kabupaten Nias Utara', type: 'kabupaten' },
    { code: '1225', name: 'Kabupaten Nias Barat', type: 'kabupaten' },
    { code: '1271', name: 'Kota Medan', type: 'kota' },
    { code: '1272', name: 'Kota Pematangsiantar', type: 'kota' },
    { code: '1273', name: 'Kota Sibolga', type: 'kota' },
    { code: '1274', name: 'Kota Tanjungbalai', type: 'kota' },
    { code: '1275', name: 'Kota Binjai', type: 'kota' },
    { code: '1276', name: 'Kota Tebing Tinggi', type: 'kota' },
    { code: '1277', name: 'Kota Padangsidimpuan', type: 'kota' },
    { code: '1278', name: 'Kota Gunungsitoli', type: 'kota' },
  ],
  '13': [
    { code: '1301', name: 'Kabupaten Pesisir Selatan', type: 'kabupaten' },
    { code: '1302', name: 'Kabupaten Solok', type: 'kabupaten' },
    { code: '1303', name: 'Kabupaten Sijunjung', type: 'kabupaten' },
    { code: '1304', name: 'Kabupaten Tanah Datar', type: 'kabupaten' },
    { code: '1305', name: 'Kabupaten Padang Pariaman', type: 'kabupaten' },
    { code: '1306', name: 'Kabupaten Agam', type: 'kabupaten' },
    { code: '1307', name: 'Kabupaten Lima Puluh Kota', type: 'kabupaten' },
    { code: '1308', name: 'Kabupaten Pasaman', type: 'kabupaten' },
    { code: '1309', name: 'Kabupaten Kepulauan Mentawai', type: 'kabupaten' },
    { code: '1310', name: 'Kabupaten Dharmasraya', type: 'kabupaten' },
    { code: '1311', name: 'Kabupaten Solok Selatan', type: 'kabupaten' },
    { code: '1312', name: 'Kabupaten Pasaman Barat', type: 'kabupaten' },
    { code: '1371', name: 'Kota Padang', type: 'kota' },
    { code: '1372', name: 'Kota Solok', type: 'kota' },
    { code: '1373', name: 'Kota Sawahlunto', type: 'kota' },
    { code: '1374', name: 'Kota Padang Panjang', type: 'kota' },
    { code: '1375', name: 'Kota Bukittinggi', type: 'kota' },
    { code: '1376', name: 'Kota Payakumbuh', type: 'kota' },
    { code: '1377', name: 'Kota Pariaman', type: 'kota' },
  ],
  '14': [
    { code: '1401', name: 'Kabupaten Kampar', type: 'kabupaten' },
    { code: '1402', name: 'Kabupaten Indragiri Hulu', type: 'kabupaten' },
    { code: '1403', name: 'Kabupaten Bengkalis', type: 'kabupaten' },
    { code: '1404', name: 'Kabupaten Indragiri Hilir', type: 'kabupaten' },
    { code: '1405', name: 'Kabupaten Pelalawan', type: 'kabupaten' },
    { code: '1406', name: 'Kabupaten Rokan Hulu', type: 'kabupaten' },
    { code: '1407', name: 'Kabupaten Rokan Hilir', type: 'kabupaten' },
    { code: '1408', name: 'Kabupaten Siak', type: 'kabupaten' },
    { code: '1409', name: 'Kabupaten Kuantan Singingi', type: 'kabupaten' },
    { code: '1410', name: 'Kabupaten Kepulauan Meranti', type: 'kabupaten' },
    { code: '1471', name: 'Kota Pekanbaru', type: 'kota' },
    { code: '1472', name: 'Kota Dumai', type: 'kota' },
  ],
  '15': [
    { code: '1501', name: 'Kabupaten Kerinci', type: 'kabupaten' },
    { code: '1502', name: 'Kabupaten Merangin', type: 'kabupaten' },
    { code: '1503', name: 'Kabupaten Sarolangun', type: 'kabupaten' },
    { code: '1504', name: 'Kabupaten Batang Hari', type: 'kabupaten' },
    { code: '1505', name: 'Kabupaten Muaro Jambi', type: 'kabupaten' },
    { code: '1506', name: 'Kabupaten Tanjung Jabung Timur', type: 'kabupaten' },
    { code: '1507', name: 'Kabupaten Tanjung Jabung Barat', type: 'kabupaten' },
    { code: '1508', name: 'Kabupaten Tebo', type: 'kabupaten' },
    { code: '1509', name: 'Kabupaten Bungo', type: 'kabupaten' },
    { code: '1571', name: 'Kota Jambi', type: 'kota' },
    { code: '1572', name: 'Kota Sungai Penuh', type: 'kota' },
  ],
  '16': [
    { code: '1601', name: 'Kabupaten Ogan Komering Ulu', type: 'kabupaten' },
    { code: '1602', name: 'Kabupaten Ogan Komering Ilir', type: 'kabupaten' },
    { code: '1603', name: 'Kabupaten Muara Enim', type: 'kabupaten' },
    { code: '1604', name: 'Kabupaten Lahat', type: 'kabupaten' },
    { code: '1605', name: 'Kabupaten Musi Rawas', type: 'kabupaten' },
    { code: '1606', name: 'Kabupaten Musi Banyuasin', type: 'kabupaten' },
    { code: '1607', name: 'Kabupaten Banyuasin', type: 'kabupaten' },
    { code: '1608', name: 'Kabupaten OKU Selatan', type: 'kabupaten' },
    { code: '1609', name: 'Kabupaten OKU Timur', type: 'kabupaten' },
    { code: '1610', name: 'Kabupaten Ogan Ilir', type: 'kabupaten' },
    { code: '1611', name: 'Kabupaten Empat Lawang', type: 'kabupaten' },
    { code: '1612', name: 'Kabupaten Penukal Abab Lematang Ilir', type: 'kabupaten' },
    { code: '1613', name: 'Kabupaten Musi Rawas Utara', type: 'kabupaten' },
    { code: '1671', name: 'Kota Palembang', type: 'kota' },
    { code: '1672', name: 'Kota Prabumulih', type: 'kota' },
    { code: '1673', name: 'Kota Pagar Alam', type: 'kota' },
    { code: '1674', name: 'Kota Lubuklinggau', type: 'kota' },
  ],
  '17': [
    { code: '1701', name: 'Kabupaten Bengkulu Selatan', type: 'kabupaten' },
    { code: '1702', name: 'Kabupaten Rejang Lebong', type: 'kabupaten' },
    { code: '1703', name: 'Kabupaten Bengkulu Utara', type: 'kabupaten' },
    { code: '1704', name: 'Kabupaten Kaur', type: 'kabupaten' },
    { code: '1705', name: 'Kabupaten Seluma', type: 'kabupaten' },
    { code: '1706', name: 'Kabupaten Mukomuko', type: 'kabupaten' },
    { code: '1707', name: 'Kabupaten Lebong', type: 'kabupaten' },
    { code: '1708', name: 'Kabupaten Kepahiang', type: 'kabupaten' },
    { code: '1709', name: 'Kabupaten Bengkulu Tengah', type: 'kabupaten' },
    { code: '1771', name: 'Kota Bengkulu', type: 'kota' },
  ],
  '18': [
    { code: '1801', name: 'Kabupaten Lampung Selatan', type: 'kabupaten' },
    { code: '1802', name: 'Kabupaten Lampung Tengah', type: 'kabupaten' },
    { code: '1803', name: 'Kabupaten Lampung Utara', type: 'kabupaten' },
    { code: '1804', name: 'Kabupaten Lampung Barat', type: 'kabupaten' },
    { code: '1805', name: 'Kabupaten Tulang Bawang', type: 'kabupaten' },
    { code: '1806', name: 'Kabupaten Tanggamus', type: 'kabupaten' },
    { code: '1807', name: 'Kabupaten Lampung Timur', type: 'kabupaten' },
    { code: '1808', name: 'Kabupaten Way Kanan', type: 'kabupaten' },
    { code: '1809', name: 'Kabupaten Pesawaran', type: 'kabupaten' },
    { code: '1810', name: 'Kabupaten Pringsewu', type: 'kabupaten' },
    { code: '1811', name: 'Kabupaten Mesuji', type: 'kabupaten' },
    { code: '1812', name: 'Kabupaten Tulang Bawang Barat', type: 'kabupaten' },
    { code: '1813', name: 'Kabupaten Pesisir Barat', type: 'kabupaten' },
    { code: '1871', name: 'Kota Bandar Lampung', type: 'kota' },
    { code: '1872', name: 'Kota Metro', type: 'kota' },
  ],
  '19': [
    { code: '1901', name: 'Kabupaten Bangka', type: 'kabupaten' },
    { code: '1902', name: 'Kabupaten Belitung', type: 'kabupaten' },
    { code: '1903', name: 'Kabupaten Bangka Selatan', type: 'kabupaten' },
    { code: '1904', name: 'Kabupaten Bangka Tengah', type: 'kabupaten' },
    { code: '1905', name: 'Kabupaten Bangka Barat', type: 'kabupaten' },
    { code: '1906', name: 'Kabupaten Belitung Timur', type: 'kabupaten' },
    { code: '1971', name: 'Kota Pangkalpinang', type: 'kota' },
  ],
  '21': [
    { code: '2101', name: 'Kabupaten Bintan', type: 'kabupaten' },
    { code: '2102', name: 'Kabupaten Karimun', type: 'kabupaten' },
    { code: '2103', name: 'Kabupaten Natuna', type: 'kabupaten' },
    { code: '2104', name: 'Kabupaten Lingga', type: 'kabupaten' },
    { code: '2105', name: 'Kabupaten Kepulauan Anambas', type: 'kabupaten' },
    { code: '2171', name: 'Kota Batam', type: 'kota' },
    { code: '2172', name: 'Kota Tanjungpinang', type: 'kota' },
  ],
  '31': [
    { code: '3101', name: 'Kabupaten Kepulauan Seribu', type: 'kabupaten' },
    { code: '3171', name: 'Kota Jakarta Selatan', type: 'kota' },
    { code: '3172', name: 'Kota Jakarta Timur', type: 'kota' },
    { code: '3173', name: 'Kota Jakarta Pusat', type: 'kota' },
    { code: '3174', name: 'Kota Jakarta Barat', type: 'kota' },
    { code: '3175', name: 'Kota Jakarta Utara', type: 'kota' },
  ],
  '32': [
    { code: '3201', name: 'Kabupaten Bogor', type: 'kabupaten' },
    { code: '3202', name: 'Kabupaten Sukabumi', type: 'kabupaten' },
    { code: '3203', name: 'Kabupaten Cianjur', type: 'kabupaten' },
    { code: '3204', name: 'Kabupaten Bandung', type: 'kabupaten' },
    { code: '3205', name: 'Kabupaten Garut', type: 'kabupaten' },
    { code: '3206', name: 'Kabupaten Tasikmalaya', type: 'kabupaten' },
    { code: '3207', name: 'Kabupaten Ciamis', type: 'kabupaten' },
    { code: '3208', name: 'Kabupaten Kuningan', type: 'kabupaten' },
    { code: '3209', name: 'Kabupaten Cirebon', type: 'kabupaten' },
    { code: '3210', name: 'Kabupaten Majalengka', type: 'kabupaten' },
    { code: '3211', name: 'Kabupaten Sumedang', type: 'kabupaten' },
    { code: '3212', name: 'Kabupaten Indramayu', type: 'kabupaten' },
    { code: '3213', name: 'Kabupaten Subang', type: 'kabupaten' },
    { code: '3214', name: 'Kabupaten Purwakarta', type: 'kabupaten' },
    { code: '3215', name: 'Kabupaten Karawang', type: 'kabupaten' },
    { code: '3216', name: 'Kabupaten Bekasi', type: 'kabupaten' },
    { code: '3217', name: 'Kabupaten Bandung Barat', type: 'kabupaten' },
    { code: '3218', name: 'Kabupaten Pangandaran', type: 'kabupaten' },
    { code: '3271', name: 'Kota Bogor', type: 'kota' },
    { code: '3272', name: 'Kota Sukabumi', type: 'kota' },
    { code: '3273', name: 'Kota Bandung', type: 'kota' },
    { code: '3274', name: 'Kota Cirebon', type: 'kota' },
    { code: '3275', name: 'Kota Bekasi', type: 'kota' },
    { code: '3276', name: 'Kota Depok', type: 'kota' },
    { code: '3277', name: 'Kota Cimahi', type: 'kota' },
    { code: '3278', name: 'Kota Tasikmalaya', type: 'kota' },
    { code: '3279', name: 'Kota Banjar', type: 'kota' },
  ],
  '33': [
    { code: '3301', name: 'Kabupaten Cilacap', type: 'kabupaten' },
    { code: '3302', name: 'Kabupaten Banyumas', type: 'kabupaten' },
    { code: '3303', name: 'Kabupaten Purbalingga', type: 'kabupaten' },
    { code: '3304', name: 'Kabupaten Banjarnegara', type: 'kabupaten' },
    { code: '3305', name: 'Kabupaten Kebumen', type: 'kabupaten' },
    { code: '3306', name: 'Kabupaten Purworejo', type: 'kabupaten' },
    { code: '3307', name: 'Kabupaten Wonosobo', type: 'kabupaten' },
    { code: '3308', name: 'Kabupaten Magelang', type: 'kabupaten' },
    { code: '3309', name: 'Kabupaten Boyolali', type: 'kabupaten' },
    { code: '3310', name: 'Kabupaten Klaten', type: 'kabupaten' },
    { code: '3311', name: 'Kabupaten Sukoharjo', type: 'kabupaten' },
    { code: '3312', name: 'Kabupaten Wonogiri', type: 'kabupaten' },
    { code: '3313', name: 'Kabupaten Karanganyar', type: 'kabupaten' },
    { code: '3314', name: 'Kabupaten Sragen', type: 'kabupaten' },
    { code: '3315', name: 'Kabupaten Grobogan', type: 'kabupaten' },
    { code: '3316', name: 'Kabupaten Blora', type: 'kabupaten' },
    { code: '3317', name: 'Kabupaten Rembang', type: 'kabupaten' },
    { code: '3318', name: 'Kabupaten Pati', type: 'kabupaten' },
    { code: '3319', name: 'Kabupaten Kudus', type: 'kabupaten' },
    { code: '3320', name: 'Kabupaten Jepara', type: 'kabupaten' },
    { code: '3321', name: 'Kabupaten Demak', type: 'kabupaten' },
    { code: '3322', name: 'Kabupaten Semarang', type: 'kabupaten' },
    { code: '3323', name: 'Kabupaten Temanggung', type: 'kabupaten' },
    { code: '3324', name: 'Kabupaten Kendal', type: 'kabupaten' },
    { code: '3325', name: 'Kabupaten Batang', type: 'kabupaten' },
    { code: '3326', name: 'Kabupaten Pekalongan', type: 'kabupaten' },
    { code: '3327', name: 'Kabupaten Pemalang', type: 'kabupaten' },
    { code: '3328', name: 'Kabupaten Tegal', type: 'kabupaten' },
    { code: '3329', name: 'Kabupaten Brebes', type: 'kabupaten' },
    { code: '3371', name: 'Kota Magelang', type: 'kota' },
    { code: '3372', name: 'Kota Surakarta', type: 'kota' },
    { code: '3373', name: 'Kota Salatiga', type: 'kota' },
    { code: '3374', name: 'Kota Semarang', type: 'kota' },
    { code: '3375', name: 'Kota Pekalongan', type: 'kota' },
    { code: '3376', name: 'Kota Tegal', type: 'kota' },
  ],
  '34': [
    { code: '3401', name: 'Kabupaten Kulon Progo', type: 'kabupaten' },
    { code: '3402', name: 'Kabupaten Bantul', type: 'kabupaten' },
    { code: '3403', name: 'Kabupaten Gunungkidul', type: 'kabupaten' },
    { code: '3404', name: 'Kabupaten Sleman', type: 'kabupaten' },
    { code: '3471', name: 'Kota Yogyakarta', type: 'kota' },
  ],
  '35': [
    { code: '3501', name: 'Kabupaten Pacitan', type: 'kabupaten' },
    { code: '3502', name: 'Kabupaten Ponorogo', type: 'kabupaten' },
    { code: '3503', name: 'Kabupaten Trenggalek', type: 'kabupaten' },
    { code: '3504', name: 'Kabupaten Tulungagung', type: 'kabupaten' },
    { code: '3505', name: 'Kabupaten Blitar', type: 'kabupaten' },
    { code: '3506', name: 'Kabupaten Kediri', type: 'kabupaten' },
    { code: '3507', name: 'Kabupaten Malang', type: 'kabupaten' },
    { code: '3508', name: 'Kabupaten Lumajang', type: 'kabupaten' },
    { code: '3509', name: 'Kabupaten Jember', type: 'kabupaten' },
    { code: '3510', name: 'Kabupaten Banyuwangi', type: 'kabupaten' },
    { code: '3511', name: 'Kabupaten Bondowoso', type: 'kabupaten' },
    { code: '3512', name: 'Kabupaten Situbondo', type: 'kabupaten' },
    { code: '3513', name: 'Kabupaten Probolinggo', type: 'kabupaten' },
    { code: '3514', name: 'Kabupaten Pasuruan', type: 'kabupaten' },
    { code: '3515', name: 'Kabupaten Sidoarjo', type: 'kabupaten' },
    { code: '3516', name: 'Kabupaten Mojokerto', type: 'kabupaten' },
    { code: '3517', name: 'Kabupaten Jombang', type: 'kabupaten' },
    { code: '3518', name: 'Kabupaten Nganjuk', type: 'kabupaten' },
    { code: '3519', name: 'Kabupaten Madiun', type: 'kabupaten' },
    { code: '3520', name: 'Kabupaten Magetan', type: 'kabupaten' },
    { code: '3521', name: 'Kabupaten Ngawi', type: 'kabupaten' },
    { code: '3522', name: 'Kabupaten Bojonegoro', type: 'kabupaten' },
    { code: '3523', name: 'Kabupaten Tuban', type: 'kabupaten' },
    { code: '3524', name: 'Kabupaten Lamongan', type: 'kabupaten' },
    { code: '3525', name: 'Kabupaten Gresik', type: 'kabupaten' },
    { code: '3526', name: 'Kabupaten Bangkalan', type: 'kabupaten' },
    { code: '3527', name: 'Kabupaten Sampang', type: 'kabupaten' },
    { code: '3528', name: 'Kabupaten Pamekasan', type: 'kabupaten' },
    { code: '3529', name: 'Kabupaten Sumenep', type: 'kabupaten' },
    { code: '3571', name: 'Kota Kediri', type: 'kota' },
    { code: '3572', name: 'Kota Blitar', type: 'kota' },
    { code: '3573', name: 'Kota Malang', type: 'kota' },
    { code: '3574', name: 'Kota Probolinggo', type: 'kota' },
    { code: '3575', name: 'Kota Pasuruan', type: 'kota' },
    { code: '3576', name: 'Kota Mojokerto', type: 'kota' },
    { code: '3577', name: 'Kota Madiun', type: 'kota' },
    { code: '3578', name: 'Kota Surabaya', type: 'kota' },
    { code: '3579', name: 'Kota Batu', type: 'kota' },
  ],
  '36': [
    { code: '3601', name: 'Kabupaten Pandeglang', type: 'kabupaten' },
    { code: '3602', name: 'Kabupaten Lebak', type: 'kabupaten' },
    { code: '3603', name: 'Kabupaten Tangerang', type: 'kabupaten' },
    { code: '3604', name: 'Kabupaten Serang', type: 'kabupaten' },
    { code: '3671', name: 'Kota Tangerang', type: 'kota' },
    { code: '3672', name: 'Kota Cilegon', type: 'kota' },
    { code: '3673', name: 'Kota Serang', type: 'kota' },
    { code: '3674', name: 'Kota Tangerang Selatan', type: 'kota' },
  ],
  '51': [
    { code: '5101', name: 'Kabupaten Jembrana', type: 'kabupaten' },
    { code: '5102', name: 'Kabupaten Tabanan', type: 'kabupaten' },
    { code: '5103', name: 'Kabupaten Badung', type: 'kabupaten' },
    { code: '5104', name: 'Kabupaten Gianyar', type: 'kabupaten' },
    { code: '5105', name: 'Kabupaten Klungkung', type: 'kabupaten' },
    { code: '5106', name: 'Kabupaten Bangli', type: 'kabupaten' },
    { code: '5107', name: 'Kabupaten Karangasem', type: 'kabupaten' },
    { code: '5108', name: 'Kabupaten Buleleng', type: 'kabupaten' },
    { code: '5171', name: 'Kota Denpasar', type: 'kota' },
  ],
  '52': [
    { code: '5201', name: 'Kabupaten Lombok Barat', type: 'kabupaten' },
    { code: '5202', name: 'Kabupaten Lombok Tengah', type: 'kabupaten' },
    { code: '5203', name: 'Kabupaten Lombok Timur', type: 'kabupaten' },
    { code: '5204', name: 'Kabupaten Sumbawa', type: 'kabupaten' },
    { code: '5205', name: 'Kabupaten Dompu', type: 'kabupaten' },
    { code: '5206', name: 'Kabupaten Bima', type: 'kabupaten' },
    { code: '5207', name: 'Kabupaten Sumbawa Barat', type: 'kabupaten' },
    { code: '5208', name: 'Kabupaten Lombok Utara', type: 'kabupaten' },
    { code: '5271', name: 'Kota Mataram', type: 'kota' },
    { code: '5272', name: 'Kota Bima', type: 'kota' },
  ],
  '53': [
    { code: '5301', name: 'Kabupaten Kupang', type: 'kabupaten' },
    { code: '5302', name: 'Kabupaten Timor Tengah Selatan', type: 'kabupaten' },
    { code: '5303', name: 'Kabupaten Timor Tengah Utara', type: 'kabupaten' },
    { code: '5304', name: 'Kabupaten Belu', type: 'kabupaten' },
    { code: '5305', name: 'Kabupaten Alor', type: 'kabupaten' },
    { code: '5306', name: 'Kabupaten Flores Timur', type: 'kabupaten' },
    { code: '5307', name: 'Kabupaten Sikka', type: 'kabupaten' },
    { code: '5308', name: 'Kabupaten Ende', type: 'kabupaten' },
    { code: '5309', name: 'Kabupaten Ngada', type: 'kabupaten' },
    { code: '5310', name: 'Kabupaten Manggarai', type: 'kabupaten' },
    { code: '5311', name: 'Kabupaten Sumba Timur', type: 'kabupaten' },
    { code: '5312', name: 'Kabupaten Sumba Barat', type: 'kabupaten' },
    { code: '5313', name: 'Kabupaten Lembata', type: 'kabupaten' },
    { code: '5314', name: 'Kabupaten Rote Ndao', type: 'kabupaten' },
    { code: '5315', name: 'Kabupaten Manggarai Barat', type: 'kabupaten' },
    { code: '5316', name: 'Kabupaten Nagekeo', type: 'kabupaten' },
    { code: '5317', name: 'Kabupaten Sumba Tengah', type: 'kabupaten' },
    { code: '5318', name: 'Kabupaten Sumba Barat Daya', type: 'kabupaten' },
    { code: '5319', name: 'Kabupaten Manggarai Timur', type: 'kabupaten' },
    { code: '5320', name: 'Kabupaten Sabu Raijua', type: 'kabupaten' },
    { code: '5321', name: 'Kabupaten Malaka', type: 'kabupaten' },
    { code: '5371', name: 'Kota Kupang', type: 'kota' },
  ],
  '61': [
    { code: '6101', name: 'Kabupaten Sambas', type: 'kabupaten' },
    { code: '6102', name: 'Kabupaten Mempawah', type: 'kabupaten' },
    { code: '6103', name: 'Kabupaten Sanggau', type: 'kabupaten' },
    { code: '6104', name: 'Kabupaten Ketapang', type: 'kabupaten' },
    { code: '6105', name: 'Kabupaten Sintang', type: 'kabupaten' },
    { code: '6106', name: 'Kabupaten Kapuas Hulu', type: 'kabupaten' },
    { code: '6107', name: 'Kabupaten Bengkayang', type: 'kabupaten' },
    { code: '6108', name: 'Kabupaten Landak', type: 'kabupaten' },
    { code: '6109', name: 'Kabupaten Sekadau', type: 'kabupaten' },
    { code: '6110', name: 'Kabupaten Melawi', type: 'kabupaten' },
    { code: '6111', name: 'Kabupaten Kayong Utara', type: 'kabupaten' },
    { code: '6112', name: 'Kabupaten Kubu Raya', type: 'kabupaten' },
    { code: '6171', name: 'Kota Pontianak', type: 'kota' },
    { code: '6172', name: 'Kota Singkawang', type: 'kota' },
  ],
  '62': [
    { code: '6201', name: 'Kabupaten Kotawaringin Barat', type: 'kabupaten' },
    { code: '6202', name: 'Kabupaten Kotawaringin Timur', type: 'kabupaten' },
    { code: '6203', name: 'Kabupaten Kapuas', type: 'kabupaten' },
    { code: '6204', name: 'Kabupaten Barito Selatan', type: 'kabupaten' },
    { code: '6205', name: 'Kabupaten Barito Utara', type: 'kabupaten' },
    { code: '6206', name: 'Kabupaten Katingan', type: 'kabupaten' },
    { code: '6207', name: 'Kabupaten Seruyan', type: 'kabupaten' },
    { code: '6208', name: 'Kabupaten Sukamara', type: 'kabupaten' },
    { code: '6209', name: 'Kabupaten Lamandau', type: 'kabupaten' },
    { code: '6210', name: 'Kabupaten Gunung Mas', type: 'kabupaten' },
    { code: '6211', name: 'Kabupaten Pulang Pisau', type: 'kabupaten' },
    { code: '6212', name: 'Kabupaten Murung Raya', type: 'kabupaten' },
    { code: '6213', name: 'Kabupaten Barito Timur', type: 'kabupaten' },
    { code: '6271', name: 'Kota Palangka Raya', type: 'kota' },
  ],
  '63': [
    { code: '6301', name: 'Kabupaten Tanah Laut', type: 'kabupaten' },
    { code: '6302', name: 'Kabupaten Kotabaru', type: 'kabupaten' },
    { code: '6303', name: 'Kabupaten Banjar', type: 'kabupaten' },
    { code: '6304', name: 'Kabupaten Barito Kuala', type: 'kabupaten' },
    { code: '6305', name: 'Kabupaten Tapin', type: 'kabupaten' },
    { code: '6306', name: 'Kabupaten Hulu Sungai Selatan', type: 'kabupaten' },
    { code: '6307', name: 'Kabupaten Hulu Sungai Tengah', type: 'kabupaten' },
    { code: '6308', name: 'Kabupaten Hulu Sungai Utara', type: 'kabupaten' },
    { code: '6309', name: 'Kabupaten Tabalong', type: 'kabupaten' },
    { code: '6310', name: 'Kabupaten Tanah Bumbu', type: 'kabupaten' },
    { code: '6311', name: 'Kabupaten Balangan', type: 'kabupaten' },
    { code: '6371', name: 'Kota Banjarmasin', type: 'kota' },
    { code: '6372', name: 'Kota Banjarbaru', type: 'kota' },
  ],
  '64': [
    { code: '6401', name: 'Kabupaten Paser', type: 'kabupaten' },
    { code: '6402', name: 'Kabupaten Kutai Kartanegara', type: 'kabupaten' },
    { code: '6403', name: 'Kabupaten Berau', type: 'kabupaten' },
    { code: '6404', name: 'Kabupaten Kutai Barat', type: 'kabupaten' },
    { code: '6405', name: 'Kabupaten Kutai Timur', type: 'kabupaten' },
    { code: '6406', name: 'Kabupaten Penajam Paser Utara', type: 'kabupaten' },
    { code: '6407', name: 'Kabupaten Mahakam Ulu', type: 'kabupaten' },
    { code: '6471', name: 'Kota Balikpapan', type: 'kota' },
    { code: '6472', name: 'Kota Samarinda', type: 'kota' },
    { code: '6474', name: 'Kota Bontang', type: 'kota' },
  ],
  '65': [
    { code: '6501', name: 'Kabupaten Bulungan', type: 'kabupaten' },
    { code: '6502', name: 'Kabupaten Malinau', type: 'kabupaten' },
    { code: '6503', name: 'Kabupaten Nunukan', type: 'kabupaten' },
    { code: '6504', name: 'Kabupaten Tana Tidung', type: 'kabupaten' },
    { code: '6571', name: 'Kota Tarakan', type: 'kota' },
  ],
  '71': [
    { code: '7101', name: 'Kabupaten Bolaang Mongondow', type: 'kabupaten' },
    { code: '7102', name: 'Kabupaten Minahasa', type: 'kabupaten' },
    { code: '7103', name: 'Kabupaten Kepulauan Sangihe', type: 'kabupaten' },
    { code: '7104', name: 'Kabupaten Kepulauan Talaud', type: 'kabupaten' },
    { code: '7105', name: 'Kabupaten Minahasa Selatan', type: 'kabupaten' },
    { code: '7106', name: 'Kabupaten Minahasa Utara', type: 'kabupaten' },
    { code: '7107', name: 'Kabupaten Minahasa Tenggara', type: 'kabupaten' },
    { code: '7108', name: 'Kabupaten Bolaang Mongondow Utara', type: 'kabupaten' },
    { code: '7109', name: 'Kabupaten Kepulauan Siau Tagulandang Biaro', type: 'kabupaten' },
    { code: '7110', name: 'Kabupaten Bolaang Mongondow Timur', type: 'kabupaten' },
    { code: '7111', name: 'Kabupaten Bolaang Mongondow Selatan', type: 'kabupaten' },
    { code: '7171', name: 'Kota Manado', type: 'kota' },
    { code: '7172', name: 'Kota Bitung', type: 'kota' },
    { code: '7173', name: 'Kota Tomohon', type: 'kota' },
    { code: '7174', name: 'Kota Kotamobagu', type: 'kota' },
  ],
  '72': [
    { code: '7201', name: 'Kabupaten Banggai', type: 'kabupaten' },
    { code: '7202', name: 'Kabupaten Poso', type: 'kabupaten' },
    { code: '7203', name: 'Kabupaten Donggala', type: 'kabupaten' },
    { code: '7204', name: 'Kabupaten Toli-Toli', type: 'kabupaten' },
    { code: '7205', name: 'Kabupaten Buol', type: 'kabupaten' },
    { code: '7206', name: 'Kabupaten Morowali', type: 'kabupaten' },
    { code: '7207', name: 'Kabupaten Banggai Kepulauan', type: 'kabupaten' },
    { code: '7208', name: 'Kabupaten Parigi Moutong', type: 'kabupaten' },
    { code: '7209', name: 'Kabupaten Tojo Una-Una', type: 'kabupaten' },
    { code: '7210', name: 'Kabupaten Sigi', type: 'kabupaten' },
    { code: '7211', name: 'Kabupaten Banggai Laut', type: 'kabupaten' },
    { code: '7212', name: 'Kabupaten Morowali Utara', type: 'kabupaten' },
    { code: '7271', name: 'Kota Palu', type: 'kota' },
  ],
  '73': [
    { code: '7301', name: 'Kabupaten Kepulauan Selayar', type: 'kabupaten' },
    { code: '7302', name: 'Kabupaten Bulukumba', type: 'kabupaten' },
    { code: '7303', name: 'Kabupaten Bantaeng', type: 'kabupaten' },
    { code: '7304', name: 'Kabupaten Jeneponto', type: 'kabupaten' },
    { code: '7305', name: 'Kabupaten Takalar', type: 'kabupaten' },
    { code: '7306', name: 'Kabupaten Gowa', type: 'kabupaten' },
    { code: '7307', name: 'Kabupaten Sinjai', type: 'kabupaten' },
    { code: '7308', name: 'Kabupaten Bone', type: 'kabupaten' },
    { code: '7309', name: 'Kabupaten Maros', type: 'kabupaten' },
    { code: '7310', name: 'Kabupaten Pangkajene Kepulauan', type: 'kabupaten' },
    { code: '7311', name: 'Kabupaten Barru', type: 'kabupaten' },
    { code: '7312', name: 'Kabupaten Soppeng', type: 'kabupaten' },
    { code: '7313', name: 'Kabupaten Wajo', type: 'kabupaten' },
    { code: '7314', name: 'Kabupaten Sidenreng Rappang', type: 'kabupaten' },
    { code: '7315', name: 'Kabupaten Pinrang', type: 'kabupaten' },
    { code: '7316', name: 'Kabupaten Enrekang', type: 'kabupaten' },
    { code: '7317', name: 'Kabupaten Luwu', type: 'kabupaten' },
    { code: '7318', name: 'Kabupaten Tana Toraja', type: 'kabupaten' },
    { code: '7322', name: 'Kabupaten Luwu Utara', type: 'kabupaten' },
    { code: '7324', name: 'Kabupaten Luwu Timur', type: 'kabupaten' },
    { code: '7326', name: 'Kabupaten Toraja Utara', type: 'kabupaten' },
    { code: '7371', name: 'Kota Makassar', type: 'kota' },
    { code: '7372', name: 'Kota Parepare', type: 'kota' },
    { code: '7373', name: 'Kota Palopo', type: 'kota' },
  ],
  '74': [
    { code: '7401', name: 'Kabupaten Buton', type: 'kabupaten' },
    { code: '7402', name: 'Kabupaten Muna', type: 'kabupaten' },
    { code: '7403', name: 'Kabupaten Konawe', type: 'kabupaten' },
    { code: '7404', name: 'Kabupaten Kolaka', type: 'kabupaten' },
    { code: '7405', name: 'Kabupaten Konawe Selatan', type: 'kabupaten' },
    { code: '7406', name: 'Kabupaten Bombana', type: 'kabupaten' },
    { code: '7407', name: 'Kabupaten Wakatobi', type: 'kabupaten' },
    { code: '7408', name: 'Kabupaten Kolaka Utara', type: 'kabupaten' },
    { code: '7409', name: 'Kabupaten Konawe Utara', type: 'kabupaten' },
    { code: '7410', name: 'Kabupaten Buton Utara', type: 'kabupaten' },
    { code: '7411', name: 'Kabupaten Kolaka Timur', type: 'kabupaten' },
    { code: '7412', name: 'Kabupaten Konawe Kepulauan', type: 'kabupaten' },
    { code: '7413', name: 'Kabupaten Muna Barat', type: 'kabupaten' },
    { code: '7414', name: 'Kabupaten Buton Tengah', type: 'kabupaten' },
    { code: '7415', name: 'Kabupaten Buton Selatan', type: 'kabupaten' },
    { code: '7471', name: 'Kota Kendari', type: 'kota' },
    { code: '7472', name: 'Kota Baubau', type: 'kota' },
  ],
  '75': [
    { code: '7501', name: 'Kabupaten Gorontalo', type: 'kabupaten' },
    { code: '7502', name: 'Kabupaten Boalemo', type: 'kabupaten' },
    { code: '7503', name: 'Kabupaten Bone Bolango', type: 'kabupaten' },
    { code: '7504', name: 'Kabupaten Pahuwato', type: 'kabupaten' },
    { code: '7505', name: 'Kabupaten Gorontalo Utara', type: 'kabupaten' },
    { code: '7571', name: 'Kota Gorontalo', type: 'kota' },
  ],
  '76': [
    { code: '7601', name: 'Kabupaten Mamuju', type: 'kabupaten' },
    { code: '7602', name: 'Kabupaten Majene', type: 'kabupaten' },
    { code: '7603', name: 'Kabupaten Polewali Mandar', type: 'kabupaten' },
    { code: '7604', name: 'Kabupaten Mamasa', type: 'kabupaten' },
    { code: '7605', name: 'Kabupaten Mamuju Utara', type: 'kabupaten' },
    { code: '7606', name: 'Kabupaten Mamuju Tengah', type: 'kabupaten' },
  ],
  '81': [
    { code: '8101', name: 'Kabupaten Maluku Tengah', type: 'kabupaten' },
    { code: '8102', name: 'Kabupaten Maluku Tenggara', type: 'kabupaten' },
    { code: '8103', name: 'Kabupaten Maluku Tenggara Barat', type: 'kabupaten' },
    { code: '8104', name: 'Kabupaten Buru', type: 'kabupaten' },
    { code: '8105', name: 'Kabupaten Kepulauan Aru', type: 'kabupaten' },
    { code: '8106', name: 'Kabupaten Seram Bagian Barat', type: 'kabupaten' },
    { code: '8107', name: 'Kabupaten Seram Bagian Timur', type: 'kabupaten' },
    { code: '8108', name: 'Kabupaten Maluku Barat Daya', type: 'kabupaten' },
    { code: '8109', name: 'Kabupaten Buru Selatan', type: 'kabupaten' },
    { code: '8171', name: 'Kota Ambon', type: 'kota' },
    { code: '8172', name: 'Kota Tual', type: 'kota' },
  ],
  '82': [
    { code: '8201', name: 'Kabupaten Halmahera Barat', type: 'kabupaten' },
    { code: '8202', name: 'Kabupaten Halmahera Tengah', type: 'kabupaten' },
    { code: '8203', name: 'Kabupaten Halmahera Utara', type: 'kabupaten' },
    { code: '8204', name: 'Kabupaten Halmahera Selatan', type: 'kabupaten' },
    { code: '8205', name: 'Kabupaten Kepulauan Sula', type: 'kabupaten' },
    { code: '8206', name: 'Kabupaten Halmahera Timur', type: 'kabupaten' },
    { code: '8207', name: 'Kabupaten Pulau Morotai', type: 'kabupaten' },
    { code: '8208', name: 'Kabupaten Pulau Taliabu', type: 'kabupaten' },
    { code: '8271', name: 'Kota Ternate', type: 'kota' },
    { code: '8272', name: 'Kota Tidore Kepulauan', type: 'kota' },
  ],
  '91': [
    { code: '9101', name: 'Kabupaten Merauke', type: 'kabupaten' },
    { code: '9102', name: 'Kabupaten Jayawijaya', type: 'kabupaten' },
    { code: '9103', name: 'Kabupaten Jayapura', type: 'kabupaten' },
    { code: '9104', name: 'Kabupaten Nabire', type: 'kabupaten' },
    { code: '9105', name: 'Kabupaten Kepulauan Yapen', type: 'kabupaten' },
    { code: '9106', name: 'Kabupaten Biak Numfor', type: 'kabupaten' },
    { code: '9107', name: 'Kabupaten Paniai', type: 'kabupaten' },
    { code: '9108', name: 'Kabupaten Mimika', type: 'kabupaten' },
    { code: '9109', name: 'Kabupaten Sarmi', type: 'kabupaten' },
    { code: '9110', name: 'Kabupaten Keerom', type: 'kabupaten' },
    { code: '9111', name: 'Kabupaten Waropen', type: 'kabupaten' },
    { code: '9112', name: 'Kabupaten Supiori', type: 'kabupaten' },
    { code: '9113', name: 'Kabupaten Mamberamo Raya', type: 'kabupaten' },
    { code: '9171', name: 'Kota Jayapura', type: 'kota' },
  ],
  '92': [
    { code: '9201', name: 'Kabupaten Manokwari', type: 'kabupaten' },
    { code: '9202', name: 'Kabupaten Fak-Fak', type: 'kabupaten' },
    { code: '9203', name: 'Kabupaten Sorong', type: 'kabupaten' },
    { code: '9204', name: 'Kabupaten Raja Ampat', type: 'kabupaten' },
    { code: '9205', name: 'Kabupaten Teluk Bintuni', type: 'kabupaten' },
    { code: '9206', name: 'Kabupaten Teluk Wondama', type: 'kabupaten' },
    { code: '9207', name: 'Kabupaten Kaimana', type: 'kabupaten' },
    { code: '9208', name: 'Kabupaten Tambrauw', type: 'kabupaten' },
    { code: '9209', name: 'Kabupaten Maybrat', type: 'kabupaten' },
    { code: '9210', name: 'Kabupaten Manokwari Selatan', type: 'kabupaten' },
    { code: '9211', name: 'Kabupaten Pegunungan Arfak', type: 'kabupaten' },
    { code: '9271', name: 'Kota Sorong', type: 'kota' },
  ],
  '93': [
    { code: '9301', name: 'Kabupaten Merauke Selatan', type: 'kabupaten' },
    { code: '9302', name: 'Kabupaten Boven Digoel', type: 'kabupaten' },
    { code: '9303', name: 'Kabupaten Mappi', type: 'kabupaten' },
    { code: '9304', name: 'Kabupaten Asmat', type: 'kabupaten' },
  ],
  '94': [
    { code: '9401', name: 'Kabupaten Puncak Jaya', type: 'kabupaten' },
    { code: '9402', name: 'Kabupaten Mimika', type: 'kabupaten' },
    { code: '9403', name: 'Kabupaten Puncak', type: 'kabupaten' },
    { code: '9404', name: 'Kabupaten Dogiyai', type: 'kabupaten' },
    { code: '9405', name: 'Kabupaten Intan Jaya', type: 'kabupaten' },
    { code: '9406', name: 'Kabupaten Deiyai', type: 'kabupaten' },
  ],
  '95': [
    { code: '9501', name: 'Kabupaten Jayawijaya', type: 'kabupaten' },
    { code: '9502', name: 'Kabupaten Pegunungan Bintang', type: 'kabupaten' },
    { code: '9503', name: 'Kabupaten Yahukimo', type: 'kabupaten' },
    { code: '9504', name: 'Kabupaten Tolikara', type: 'kabupaten' },
    { code: '9505', name: 'Kabupaten Nduga', type: 'kabupaten' },
    { code: '9506', name: 'Kabupaten Lanny Jaya', type: 'kabupaten' },
    { code: '9507', name: 'Kabupaten Mamberamo Tengah', type: 'kabupaten' },
    { code: '9508', name: 'Kabupaten Yalimo', type: 'kabupaten' },
  ],
  '96': [
    { code: '9601', name: 'Kabupaten Sorong Selatan', type: 'kabupaten' },
    { code: '9602', name: 'Kabupaten Maybrat', type: 'kabupaten' },
  ],
};

const operators = [
  { mcc: '510', mnc: '10', name: 'PT Telekomunikasi Selular', brand: 'Telkomsel' },
  { mcc: '510', mnc: '01', name: 'PT Indosat Tbk', brand: 'Indosat Ooredoo Hutchison' },
  { mcc: '510', mnc: '21', name: 'PT Indosat Tbk', brand: 'Indosat Ooredoo Hutchison' },
  { mcc: '510', mnc: '11', name: 'PT XL Axiata Tbk', brand: 'XL Axiata' },
  { mcc: '510', mnc: '89', name: 'PT Hutchison 3 Indonesia', brand: 'Tri (3)' },
  { mcc: '510', mnc: '28', name: 'PT Smartfren Telecom Tbk', brand: 'Smartfren' },
  { mcc: '510', mnc: '09', name: 'PT Smartfren Telecom Tbk', brand: 'Smartfren' },
  { mcc: '510', mnc: '27', name: 'PT Sampoerna Telekomunikasi Indonesia', brand: 'Net1' },
  { mcc: '510', mnc: '08', name: 'PT Natrindo Telepon Seluler', brand: 'Axis' },
  { mcc: '510', mnc: '99', name: 'PT Pasifik Satelit Nusantara', brand: 'Aces' },
  { mcc: '510', mnc: '00', name: 'PT Telkom Indonesia', brand: 'Telkom Flexi' },
];

const msisdnPrefixes = [
  { prefix: '0811', operator_name: 'Telkomsel', mnc: '10', network_type: 'GSM' },
  { prefix: '0812', operator_name: 'Telkomsel', mnc: '10', network_type: 'GSM' },
  { prefix: '0813', operator_name: 'Telkomsel', mnc: '10', network_type: 'GSM' },
  { prefix: '0821', operator_name: 'Telkomsel', mnc: '10', network_type: 'GSM' },
  { prefix: '0822', operator_name: 'Telkomsel', mnc: '10', network_type: 'GSM' },
  { prefix: '0823', operator_name: 'Telkomsel', mnc: '10', network_type: 'GSM' },
  { prefix: '0851', operator_name: 'Telkomsel', mnc: '10', network_type: 'GSM' },
  { prefix: '0852', operator_name: 'Telkomsel', mnc: '10', network_type: 'GSM' },
  { prefix: '0853', operator_name: 'Telkomsel', mnc: '10', network_type: 'GSM' },
  { prefix: '0814', operator_name: 'Indosat Ooredoo Hutchison', mnc: '01', network_type: 'GSM' },
  { prefix: '0815', operator_name: 'Indosat Ooredoo Hutchison', mnc: '01', network_type: 'GSM' },
  { prefix: '0816', operator_name: 'Indosat Ooredoo Hutchison', mnc: '01', network_type: 'GSM' },
  { prefix: '0855', operator_name: 'Indosat Ooredoo Hutchison', mnc: '01', network_type: 'GSM' },
  { prefix: '0856', operator_name: 'Indosat Ooredoo Hutchison', mnc: '01', network_type: 'GSM' },
  { prefix: '0857', operator_name: 'Indosat Ooredoo Hutchison', mnc: '01', network_type: 'GSM' },
  { prefix: '0858', operator_name: 'Indosat Ooredoo Hutchison', mnc: '01', network_type: 'GSM' },
  { prefix: '0817', operator_name: 'XL Axiata', mnc: '11', network_type: 'GSM' },
  { prefix: '0818', operator_name: 'XL Axiata', mnc: '11', network_type: 'GSM' },
  { prefix: '0819', operator_name: 'XL Axiata', mnc: '11', network_type: 'GSM' },
  { prefix: '0859', operator_name: 'XL Axiata', mnc: '11', network_type: 'GSM' },
  { prefix: '0877', operator_name: 'XL Axiata', mnc: '11', network_type: 'GSM' },
  { prefix: '0878', operator_name: 'XL Axiata', mnc: '11', network_type: 'GSM' },
  { prefix: '0895', operator_name: 'Tri (3)', mnc: '89', network_type: 'GSM' },
  { prefix: '0896', operator_name: 'Tri (3)', mnc: '89', network_type: 'GSM' },
  { prefix: '0897', operator_name: 'Tri (3)', mnc: '89', network_type: 'GSM' },
  { prefix: '0898', operator_name: 'Tri (3)', mnc: '89', network_type: 'GSM' },
  { prefix: '0899', operator_name: 'Tri (3)', mnc: '89', network_type: 'GSM' },
  { prefix: '0881', operator_name: 'Smartfren', mnc: '28', network_type: 'CDMA/LTE' },
  { prefix: '0882', operator_name: 'Smartfren', mnc: '28', network_type: 'CDMA/LTE' },
  { prefix: '0883', operator_name: 'Smartfren', mnc: '28', network_type: 'CDMA/LTE' },
  { prefix: '0884', operator_name: 'Smartfren', mnc: '28', network_type: 'CDMA/LTE' },
  { prefix: '0885', operator_name: 'Smartfren', mnc: '28', network_type: 'CDMA/LTE' },
  { prefix: '0886', operator_name: 'Smartfren', mnc: '28', network_type: 'CDMA/LTE' },
  { prefix: '0887', operator_name: 'Smartfren', mnc: '28', network_type: 'CDMA/LTE' },
  { prefix: '0888', operator_name: 'Smartfren', mnc: '28', network_type: 'CDMA/LTE' },
  { prefix: '0889', operator_name: 'Smartfren', mnc: '28', network_type: 'CDMA/LTE' },
  { prefix: '0831', operator_name: 'Axis', mnc: '08', network_type: 'GSM' },
  { prefix: '0832', operator_name: 'Axis', mnc: '08', network_type: 'GSM' },
  { prefix: '0833', operator_name: 'Axis', mnc: '08', network_type: 'GSM' },
  { prefix: '0838', operator_name: 'Axis', mnc: '08', network_type: 'GSM' },
];

async function seedRegions() {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');

    for (const p of provinces) {
      await client.query(
        'INSERT INTO provinces (code, name) VALUES ($1, $2) ON CONFLICT (code) DO NOTHING',
        [p.code, p.name]
      );
    }
    console.log(`Seeded ${provinces.length} provinces`);

    let kabCount = 0;
    for (const [provCode, kabs] of Object.entries(kabupatenData)) {
      for (const k of kabs) {
        await client.query(
          'INSERT INTO kabupaten (code, province_code, name, type) VALUES ($1, $2, $3, $4) ON CONFLICT (code) DO NOTHING',
          [k.code, provCode, k.name, k.type]
        );
        kabCount++;
      }
    }
    console.log(`Seeded ${kabCount} kabupaten/kota`);

    for (const op of operators) {
      await client.query(
        'INSERT INTO operators (mcc, mnc, name, brand) VALUES ($1, $2, $3, $4) ON CONFLICT (mcc, mnc) DO NOTHING',
        [op.mcc, op.mnc, op.name, op.brand]
      );
    }
    console.log(`Seeded ${operators.length} operators`);

    for (const p of msisdnPrefixes) {
      await client.query(
        'INSERT INTO msisdn_prefixes (prefix, operator_name, mnc, network_type) VALUES ($1, $2, $3, $4) ON CONFLICT DO NOTHING',
        [p.prefix, p.operator_name, p.mnc, p.network_type]
      );
    }
    console.log(`Seeded ${msisdnPrefixes.length} MSISDN prefixes`);

    await client.query('COMMIT');
  } catch (err) {
    await client.query('ROLLBACK');
    throw err;
  } finally {
    client.release();
  }
}

module.exports = { seedRegions, provinces, kabupatenData };
